name: ninja_bip32
description: Dart implementation of BIP32.
version: 1.0.0
repository: https://github.com/chandrayaan-finance/hdwallet

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  pedantic: ^1.11.1
  crypto:
  ninja: ^3.0.2
  secp256k1: 0.3.0
  bs58check: ^1.0.2
  hash:
    git: https://github.com/redDwarf03/hash
  collection: ^1.15.0

dev_dependencies:
  test: ^1.17.10
